-- Ajout de la valeur par défaut CURRENT_TIMESTAMP pour date_creation sur toutes les tables

ALTER TABLE alerte ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE article ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE campagne ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE commande ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE cooperative ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE culture ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE maladie ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE observation_climat ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE offre ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE paiement ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE parcelle ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE redevance ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ALTER COLUMN date_creation SET DEFAULT CURRENT_TIMESTAMP;